# baseline/04_fastapi.yaml

# configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: backend
data:
  PROJECT: "eks-benchmark"
  ENV: "baseline"
  DEBUG: "false" 
  LOG_LEVEL: "info"
  POOL_SIZE: "5"
  MAX_OVERFLOW: "0"
  WORKER: "1"
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: backend
  labels:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/part-of: eks-benchmark
    app.kubernetes.io/component: api
spec:
  replicas: 4
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi
        app.kubernetes.io/part-of: eks-benchmark
        app.kubernetes.io/component: api
      annotations:
        kubernetes.io/change-cause: "baseline fastapi deploy"
    spec:
      terminationGracePeriodSeconds: 45
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: fastapi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
      containers:
        - name: fastapi
          image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/auto-benchmark:fastapi-baseline
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          # env from configmap
          envFrom:
            - configMapRef:
                name: fastapi-config

          # env from eso secret
          env:
            - name: POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__HOST
            - name: POSTGRES__PORT
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__PORT
            - name: POSTGRES__DB
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__DB
            - name: POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__USER
            - name: POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__PASSWORD
          
          # startup
          startupProbe:
            httpGet:
              path: /api/health/
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30   # ~150s max startup

          # health check
          readinessProbe:
            httpGet:
              path: /api/health/
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health/
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
            initialDelaySeconds: 30

          lifecycle:
            preStop:  # time before stop,
              exec:
                command: ["sh", "-c", "sleep 20"]

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
---
# service
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: backend
  labels:
    app.kubernetes.io/name: fastapi
spec:
  selector:
    app.kubernetes.io/name: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
---
# pod budge
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fastapi-pdb
  namespace: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
---
# hpa
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
      selectPolicy: Max