# baseline/04_fastapi.yaml

# configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: backend
data:
  PROJECT: "eks-benchmark1"
  ENV: "baseline"
  DEBUG: "true"
  LOG_LEVEL: "info"
  POOL_SIZE: "5"
  MAX_OVERFLOW: "0"
  WORKER: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: backend
  labels:
    app: fastapi
spec:
  replicas: 1  # dev default
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/auto-benchmark:fastapi-baseline
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          # env from configmap
          envFrom:
            - configMapRef:
                name: fastapi-config

          # env from eso secret
          env:
            - name: POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__HOST
            - name: POSTGRES__PORT
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__PORT
            - name: POSTGRES__DB
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__DB
            - name: POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__USER
            - name: POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__PASSWORD

          # health check
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 30

          startupProbe:
            httpGet:
              path: /api/health/
              port: 8000
            periodSeconds: 10
            failureThreshold: 9  # ~90s total (9 * 10s)

          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: backend
  labels:
    app: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP