# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: outbox
---
# external secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-cred
  namespace: outbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-global
    kind: ClusterSecretStore
  target:
    name: app-cred
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES__HOST
      remoteRef:
        key: eks-benchmark-kafka
        property: db_host
    - secretKey: POSTGRES__PORT
      remoteRef:
        key: eks-benchmark-kafka
        property: db_port
    - secretKey: POSTGRES__DB
      remoteRef:
        key: eks-benchmark-kafka
        property: db_dbname
    - secretKey: POSTGRES__USER
      remoteRef:
        key: eks-benchmark-kafka
        property: db_username
    - secretKey: POSTGRES__PASSWORD
      remoteRef:
        key: eks-benchmark-kafka
        property: db_password
    - secretKey: FLYWAY_URL
      remoteRef:
        key: eks-benchmark-kafka
        property: flyway_url
    - secretKey: APP_USER_PASSWORD
      remoteRef:
        key: eks-benchmark-kafka
        property: db_app_pwd
    - secretKey: APP_READONLY_PASSWORD
      remoteRef:
        key: eks-benchmark-kafka
        property: db_readonly_pwd
    - secretKey: REDIS__HOST
      remoteRef:
        key: eks-benchmark-kafka
        property: redis_host
    - secretKey: REDIS__PORT
      remoteRef:
        key: eks-benchmark-kafka
        property: redis_port
    - secretKey: KAFKA__USE_MSK_AUTH
      remoteRef:
        key: eks-benchmark-kafka
        property: kafka_use_msk_auth
    - secretKey: KAFKA__BOOTSTRAP_SERVERS
      remoteRef:
        key: eks-benchmark-kafka
        property: kafka_bootstrap_servers
    - secretKey: KAFKA__TOPIC
      remoteRef:
        key: eks-benchmark-kafka
        property: kafka_topic
---
# sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: msk-redis-outbox
  namespace: outbox
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::099139718958:role/eks-benchmark-kafka-msk-redis-outbox
---
# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-outbox
  namespace: outbox
  labels:
    app.kubernetes.io/name: redis-outbox
    app.kubernetes.io/part-of: eks-benchmark
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-outbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-outbox
        app.kubernetes.io/part-of: eks-benchmark
        app.kubernetes.io/component: worker
      annotations:
        kubernetes.io/change-cause: "redis-outbox deploy"
    spec:
      serviceAccountName: msk-redis-outbox
      terminationGracePeriodSeconds: 90
      containers:
        - name: redis-outbox
          image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/auto-benchmark:redis-outbox
          imagePullPolicy: Always

          env:
            - name: POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__HOST
            - name: POSTGRES__PORT
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__PORT
            - name: POSTGRES__DB
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__DB
            - name: POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__USER
            - name: POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: POSTGRES__PASSWORD
            - name: REDIS__HOST
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: REDIS__HOST
            - name: REDIS__PORT
              valueFrom:
                secretKeyRef:
                  name: app-cred
                  key: REDIS__PORT

          resources:
            requests:
              cpu: "512m"
              memory: "512Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"
---
# # hpa
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: redis-outbox-hpa
#   namespace: outbox
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: redis-outbox
#   minReplicas: 1
#   maxReplicas: 4
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 60
#   behavior:
#     scaleUp:
#       stabilizationWindowSeconds: 0
#       policies:
#         - type: Percent
#           value: 100
#           periodSeconds: 30
#         - type: Pods
#           value: 2
#           periodSeconds: 30
#       selectPolicy: Max
#     scaleDown:
#       stabilizationWindowSeconds: 60
#       policies:
#         - type: Percent
#           value: 25
#           periodSeconds: 60
#       selectPolicy: Max