apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: backend
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3000"]
      # env from configmap
      envFrom:
        - configMapRef:
            name: init-kafka-config

      env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            secretKeyRef:
              name: app-cred
              key: KAFKA__BOOTSTRAP_SERVERS
