# .github/workflow/wf-testing.yaml
name: Workflow Auto Testing

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  #     # - "testing"

# multiple trigger
concurrency:
  group: wf-testing-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true # Cancel older runs

jobs:
  deploy_infra:
    name: Deploy Resources
    uses: ./.github/workflows/job_deploy_infra.yaml
    permissions:
      contents: read
      id-token: write # OIDC
    strategy:
      fail-fast: false
      matrix:
        solution:
          - arch: baseline
          - arch: scale
          # - arch: redis
          # - arch: kafka
    with:
      project: ${{ vars.PROJECT}}
      arch: ${{ matrix.solution.arch }}
      aws_region: ${{ vars.AWS_REGION }}
    secrets:
      db_name: ${{ secrets.DB_NAME }}
      db_username: ${{ secrets.DB_USERNAME }}
      db_password: ${{ secrets.DB_PASSWORD }}
      db_app_pwd: ${{ secrets.DB_APP_PWD }}
      db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
      cf_api_token: ${{ secrets.CF_API_TOKEN }}
      cf_zone_id: ${{ secrets.CF_ZONE_ID }}
      aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
      aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}
      cluster_admin_arn: ${{ secrets.CLUSTER_ADMIN_ARN }}

  performance_testing_mixed:
    name: Performance Testing-Mixed
    needs:
      - deploy_infra
    uses: ./.github/workflows/job_test_performance.yaml
    strategy:
      fail-fast: false
      matrix:
        solution:
          - arch: baseline
            base_url: "https://eks-benchmark-baseline.arguswatcher.net"
            test_report: baseline_cicd_mixed.html
          - arch: scale
            base_url: "https://eks-benchmark-scale.arguswatcher.net"
            test_report: scale_cicd_mixed.html
          # - arch: redis
          #   base_url: "https://benchmark-redis.arguswatcher.net"
          #   test_report: redis_cicd_mixed.html
          # - arch: kafka
          #   base_url: "https://benchmark-kafka.arguswatcher.net"
          #   test_report: kafka_cicd_mixed.html
    with:
      base_url: ${{ matrix.solution.base_url }}
      arch: ${{ matrix.solution.arch }}
      test_report: ${{ matrix.solution.test_report }}
      test_script: test_hp_mixed.js

# debug: remove upload s3

# destroy:
#   name: Destroy Resources
#   needs:
#     - smoke_testing
#     - performance_testing_mixed
#   if: >-
#     ${{
#       always() &&
#       (
#         needs.smoke_testing.result != 'success' ||
#         needs.performance_testing_mixed.result != 'skipped'
#       )
#     }}
#   uses: ./.github/workflows/job_destroy.yaml
#   permissions:
#     contents: read
#     id-token: write # OIDC
#   strategy:
#     fail-fast: false
#     matrix:
#       solution:
#         - env: baseline
#         # - env: tune
#         - env: scale
#         - env: redis
#         - env: kafka
#   with:
#     project: ${{ vars.PROJECT}}
#     env: ${{ matrix.solution.env }}
#     aws_region: ${{ vars.AWS_REGION }}
#   secrets:
#     db_name: ${{ secrets.DB_NAME }}
#     db_username: ${{ secrets.DB_USERNAME }}
#     db_password: ${{ secrets.DB_PASSWORD }}
#     db_app_pwd: ${{ secrets.DB_APP_PWD }}
#     db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
#     cf_api_token: ${{ secrets.CF_API_TOKEN }}
#     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
#     aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
#     aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}
